services:
  postgres:
    image: postgres:16.1-alpine3.19
    environment:
      - POSTGRES_USER=mosleh
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=Elyasam_Restaurant
  api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgres://mosleh:1234@postgres:5432/Elyasam_Restaurant?sslmode=disable