// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"time"
)

type Category struct {
	ID            int64  `json:"id"`
	CategoryTitle string `json:"category_title"`
	CategoryIcon  string `json:"category_icon"`
}

type Comment struct {
	ID             int64     `json:"id"`
	CommentContent string    `json:"comment_content"`
	ServiceID      int64     `json:"service_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type DiscountOffer struct {
	ID        int64     `json:"id"`
	ServiceID int64     `json:"service_id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiredAt time.Time `json:"expired_at"`
}

type Service struct {
	ID              int64  `json:"id"`
	ServiceImage    string `json:"service_image"`
	ServiceTitle    string `json:"service_title"`
	ServiceCategory int64  `json:"service_category"`
	Star            int32  `json:"star"`
	Recipe          string `json:"recipe"`
	Price           int64  `json:"price"`
}

type SliderImage struct {
	ID        int64  `json:"id"`
	ImagePath string `json:"image_path"`
}
