// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, categoryTitle string) (Category, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetComment(ctx context.Context, id int64) (Comment, error)
	GetService(ctx context.Context, id int64) (Service, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListComments(ctx context.Context, arg ListCommentsParams) ([]Comment, error)
}

var _ Querier = (*Queries)(nil)
